name: Scrape
on:
  workflow_dispatch:
  schedule:
     - cron: '0 0 * * *'

jobs:
  scrape:
    permissions:
       contents: write
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
           cache: 'npm'
       - run: npm ci
       - run: npm run scrape
       - run: |
          git config --global user.name 'xxaver'
          git config --global user.email 'xxaver@users.noreply.github.com'
          git commit -am "Automated: Update knowledge"
          git push
