name: Scrape (Gymnasium Weingarten)
on:
  workflow_dispatch:
  schedule:
     - cron: '0 0,12 * * *'

jobs:
  scrape:
    permissions:
       contents: write
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
         with:
           ref: gym-wgt
       - uses: actions/setup-node@v4
         with:
           cache: 'npm'
       - run: npm ci
       - run: npm run scrape
       - name: Commit Changes
         run: |
          git commit -am "Automated: Update knowledge"
          git push
